repository: intotheodd
staticman:
  branch: gh-pages
permalink: /:slug-:month:day:short_year
include: ['_pages']

title: Jekyll-db
description:
google_analytics:
show_downloads: true
plugins:
  - pagemaster

collections:
    monsters:
    output: true
    source: monsters.csv
    id_key: id
    layout: entry
